version: '2.1'
services:
  database:
   container_name: postgresql_alpine
   image: postgres:alpine
   restart: always
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U db_user -d my_db"]
     interval: 5s
     timeout: 5s
     retries: 5
   environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password
   ports:
     - 8081:5432

  website:
   container_name: php_73
   image: derivability:php_img
   build:
     context: ./
   ports:
    - 8080:80
   depends_on:
    database:
      condition: service_healthy

